import crypto from "node:crypto";
import { ApiError } from "../../utils/ApiError.js";
import { getCredential } from "../integrations/credential.service.js";

const manual = {
  async createShipment({ input }) { return { provider: "MANUAL", providerShipmentId: null, carrier: input.carrier || "Manual fulfilment", trackingNumber: input.trackingNumber || null, trackingUrl: input.trackingUrl || null, awb: input.awb || null, estimatedDelivery: input.estimatedDelivery || null, status: "CREATED" }; },
  async cancelShipment() { return { cancelled: true }; }, async getTracking(shipment) { return { status: shipment.status, trackingNumber: shipment.trackingNumber }; }, async getLabel() { return null; }, async schedulePickup() { return { supported: false }; }, async getRates() { return []; }, async testConnection() { return { ok: true }; }, verifyWebhook() { return false; },
};

function providerError(response) { const message = response?.message || response?.error || response?.errors?.[0]?.message; return new Error(message ? `Carrier request failed: ${message}` : "Carrier request failed."); }
async function shiprocketCredentials(environment = "LIVE") { const credential = await getCredential("SHIPROCKET", environment).catch(() => null) || await getCredential("SHIPROCKET", environment === "LIVE" ? "TEST" : "LIVE").catch(() => null); if (!credential?.data?.apiEmail || !credential.data.apiPassword) throw ApiError.badRequest("SHIPROCKET is not configured."); return credential.data; }
async function shiprocketRequest(path, { method = "GET", body, environment } = {}) {
  const credentials = await shiprocketCredentials(environment); const base = (credentials.apiBaseUrl || "https://apiv2.shiprocket.in/v1/external").replace(/\/$/, "");
  const login = await fetch(`${base}/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: credentials.apiEmail, password: credentials.apiPassword }) }); const auth = await login.json().catch(() => null); if (!login.ok || !auth?.token) throw providerError(auth);
  const response = await fetch(`${base}${path}`, { method, headers: { authorization: `Bearer ${auth.token}`, ...(body ? { "content-type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); const json = await response.json().catch(() => null); if (!response.ok || json?.status_code >= 400) throw providerError(json); return json;
}
function shiprocketAddress(address = {}) { return { name: address.fullName, address: [address.addressLine1, address.addressLine2, address.landmark].filter(Boolean).join(", "), city: address.city, state: address.state, pincode: String(address.postalCode), country: address.country || "India", email: address.email || undefined, phone: address.phone }; }

const shiprocket = {
  async testConnection({ environment } = {}) { await shiprocketRequest("/courier/serviceability/?pickup_postcode=110001&delivery_postcode=110001&weight=0.5&cod=0", { environment }); return { ok: true }; },
  async createShipment({ input, settings }) {
    const shipping = shiprocketAddress(input.shippingAddress), billing = shiprocketAddress(input.billingAddress || input.shippingAddress);
    const payload = { order_id: input.order.number, order_date: new Date(input.order.date).toISOString().slice(0, 10), pickup_location: settings.pickup?.location || settings.pickupLocation || "Primary", billing_customer_name: billing.name, billing_last_name: "", billing_address: billing.address, billing_city: billing.city, billing_pincode: billing.pincode, billing_state: billing.state, billing_country: billing.country, billing_email: billing.email || input.customer.email, billing_phone: billing.phone || input.customer.phone, shipping_is_billing: false, shipping_customer_name: shipping.name, shipping_last_name: "", shipping_address: shipping.address, shipping_city: shipping.city, shipping_pincode: shipping.pincode, shipping_state: shipping.state, shipping_country: shipping.country, shipping_email: shipping.email || input.customer.email, shipping_phone: shipping.phone || input.customer.phone, order_items: input.items.map((item) => ({ name: item.name, sku: item.sku || item.name.slice(0, 80), units: item.quantity, selling_price: Number(item.sellingPrice), discount: Number(item.discount || 0), tax: Number(item.tax || 0), hsn: "" })), payment_method: input.order.paymentMethod === "cod" ? "COD" : "Prepaid", sub_total: input.items.reduce((sum, item) => sum + Number(item.sellingPrice) * item.quantity, 0), length: Number(input.package.length), breadth: Number(input.package.width), height: Number(input.package.height), weight: Number(input.package.weight) };
    const created = await shiprocketRequest("/orders/create/adhoc", { method: "POST", body: payload, environment: settings.environment }); const shipmentId = created.shipment_id || created.shipment?.id; let awbResult = null; if (shipmentId && settings.courierCompanyId) awbResult = await shiprocketRequest("/courier/assign/awb", { method: "POST", body: { shipment_id: shipmentId, courier_company_id: Number(settings.courierCompanyId) }, environment: settings.environment });
    return { provider: "SHIPROCKET", providerOrderId: String(created.order_id || input.order.number), providerShipmentId: shipmentId ? String(shipmentId) : null, awb: awbResult?.response?.data?.awb_code || awbResult?.awb_code || null, trackingNumber: awbResult?.response?.data?.awb_code || awbResult?.awb_code || null, carrier: awbResult?.response?.data?.courier_name || null, status: "CREATED" };
  },
  async generateAwb(shipment, settings = {}) { if (!settings.courierCompanyId) throw ApiError.badRequest("Set a Shiprocket courier company before generating an AWB."); const result = await shiprocketRequest("/courier/assign/awb", { method: "POST", body: { shipment_id: Number(shipment.providerShipmentId), courier_company_id: Number(settings.courierCompanyId) }, environment: settings.environment }); return { awb: result?.response?.data?.awb_code || result?.awb_code, carrier: result?.response?.data?.courier_name || null }; },
  async schedulePickup(shipment, settings = {}) { const result = await shiprocketRequest("/courier/generate/pickup", { method: "POST", body: { shipment_id: [Number(shipment.providerShipmentId)] }, environment: settings.environment }); return { supported: true, pickupStatus: result?.pickup_status || "PICKUP_SCHEDULED" }; },
  async getTracking(shipment, settings = {}) { const result = await shiprocketRequest(`/courier/track/shipment/${encodeURIComponent(shipment.providerShipmentId)}`, { environment: settings.environment }); const tracking = result?.tracking_data || result; return { rawStatus: tracking.shipment_status || tracking.shipment_track?.[0]?.current_status, trackingNumber: shipment.awb || tracking.shipment_track?.[0]?.awb_code, trackingUrl: tracking.track_url || null, raw: result }; },
  async getLabel(shipment, settings = {}) { return shiprocketRequest("/courier/generate/label", { method: "POST", body: { shipment_id: [Number(shipment.providerShipmentId)] }, environment: settings.environment }); },
  async cancelShipment(shipment, settings = {}) { await shiprocketRequest("/orders/cancel/shipment/adhoc", { method: "POST", body: { ids: [Number(shipment.providerShipmentId)] }, environment: settings.environment }); return { cancelled: true }; },
  verifyWebhook(raw, signature, secret) { if (!signature || !secret) return false; const expected = crypto.createHmac("sha256", secret).update(raw).digest("hex"); return expected.length === String(signature).length && crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(String(signature))); },
};
export function getShippingProvider(name = "MANUAL") { if (name === "MANUAL") return manual; if (name === "SHIPROCKET") return shiprocket; if (name === "DELHIVERY") throw ApiError.badRequest("DELHIVERY is disabled: the contracted API account, endpoint, and webhook-signature specification are required before enabling it."); throw ApiError.badRequest(`Shipping provider ${name} is not configured.`); }
