import React from "react";
import { Link } from "react-router-dom";
import CircularCategoryNav from "./CircularCategoryNav";
import PromoStrip from "./PromoStrip";
import HeroBannerCarousel from "./HeroBannerCarousel";
import TrustServiceStrip from "./TrustServiceStrip";
import PromoBanners2Up from "./PromoBanners2Up";
import ProductCard from "./ProductCard";
import { ProductGridSkeleton } from "./ui/Skeleton";
import { formatInr } from "../lib/format";
import { IconArrowRight } from "./icons";

const route = (value, fallback = "/shop") => typeof value === "string" && (value.startsWith("/") || /^https?:\/\//i.test(value)) ? value : fallback;
function SafeLink({ to, children, ...props }) { const url = route(to); return url.startsWith("/") ? <Link to={url} {...props}>{children}</Link> : <a href={url} {...props}>{children}</a>; }
const enabled = (items = []) => items.filter((item) => item.enabled !== false).sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0));

export default function HomepageRenderer({ sections = [], categories = [], newArrivals = [], bestSellers = [], featuredCollection = null, booksList = [], isLoading = false, subscribed = false, newsletterEmail = "", setNewsletterEmail = () => {}, handleNewsletterSubmit = () => {}, newsletterStatus = "idle", newsletterError = "" }) {
  if (!sections?.length) return null;
  const renderProducts = (products, limit) => isLoading ? <ProductGridSkeleton count={limit || 4} /> : <div className="grid grid-cols-2 gap-4 sm:gap-6 lg:grid-cols-4">{products.slice(0, limit || 4).map((product) => <ProductCard key={product.id} product={product} />)}</div>;
  const renderSection = (section) => {
    const s = section.settings || {};
    switch (section.type) {
      case "CIRCULAR_CATEGORY_NAV": case "CATEGORY_CIRCLES": return <CircularCategoryNav key={section.id} categories={categories} />;
      case "PROMO_STRIP": case "PROMO_TICKER": return <PromoStrip key={section.id} />;
      case "HERO_CAROUSEL": case "HERO": return <HeroBannerCarousel key={section.id} />;
      case "TRUST_STRIP": case "TRUST_BADGES": return <TrustServiceStrip key={section.id} items={s.items} />;
      case "PROMO_BANNERS_2UP": case "MULTI_BANNER": return <PromoBanners2Up key={section.id} promoCards={s.items} />;
      case "NEW_ARRIVALS": case "BEST_SELLERS": {
        const isNew = section.type === "NEW_ARRIVALS"; const defaults = isNew ? ["Fresh Drops", "New Arrivals", "View All New Arrivals", "/new-arrivals"] : ["Most Cherished", "Best Sellers", "View All Best Sellers", "/best-sellers"];
        return <section key={section.id} className="mx-auto max-w-7xl px-4 sm:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4 border-b border-charcoal/10 pb-4"><div><span className="text-xs font-semibold uppercase tracking-widest text-terracotta">{s.eyebrow || defaults[0]}</span><h2 className="mt-1 font-serif-display text-3xl font-bold text-charcoal sm:text-4xl">{s.title || defaults[1]}</h2></div><SafeLink to={s.ctaUrl || defaults[3]} className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-terracotta hover:underline">{s.ctaLabel || defaults[2]} <IconArrowRight className="h-4 w-4" /></SafeLink></div>{renderProducts(isNew ? newArrivals : bestSellers, s.limit)}</section>;
      }
      case "FEATURED_COLLECTION": case "COLLECTION": {
        if (!featuredCollection) return null; const target = s.ctaUrl || (s.collectionSlug ? `/collections/${s.collectionSlug}` : `/collections/${featuredCollection.slug}`);
        return <section key={section.id} className="mx-auto max-w-7xl px-4 sm:px-8"><div className={`grid items-center overflow-hidden rounded-2xl border border-charcoal/10 lg:grid-cols-12 ${s.backgroundStyle === "WHITE" ? "bg-white" : "bg-[#FAF6F0]"}`}><div className="space-y-5 p-8 sm:p-14 lg:col-span-6"><span className="text-xs font-bold uppercase tracking-widest text-sage">{s.eyebrow || "Featured Editorial Collection"}</span><h2 className="font-serif-display text-3xl font-bold text-charcoal sm:text-4xl lg:text-5xl">{s.title || featuredCollection.name}</h2>{s.description !== "" && <p className="text-sm leading-relaxed text-charcoal-soft sm:text-base">{s.description || featuredCollection.description}</p>}<SafeLink to={target} className="inline-flex items-center gap-2 rounded-full bg-terracotta px-7 py-3 text-xs font-semibold uppercase tracking-wider text-white shadow-xs transition hover:bg-terracotta-dark">{s.ctaLabel || "Explore Collection"} <IconArrowRight className="h-4 w-4" /></SafeLink></div><div className="group min-h-[340px] overflow-hidden aspect-square sm:aspect-video lg:col-span-6 lg:aspect-auto"><img src={s.image || featuredCollection.heroImage} alt={s.imageAlt || s.title || featuredCollection.name} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /></div></div></section>;
      }
      case "SHOP_THE_LOOK": return <section key={section.id} className="mx-auto max-w-7xl px-4 sm:px-8"><div className="mb-10 flex flex-col items-center text-center"><span className="text-xs font-semibold uppercase tracking-widest text-terracotta">{s.eyebrow || "Lifestyle Inspiration"}</span><h2 className="mt-1.5 font-serif-display text-3xl font-bold text-charcoal sm:text-4xl">{s.title || "Shop the Look"}</h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{enabled(s.items || []).map((look) => <SafeLink key={look.id || look.title} to={look.url} className="group relative overflow-hidden rounded-2xl border border-charcoal/10 bg-white transition hover:shadow-xl"><div className="aspect-[3/4] overflow-hidden"><img src={look.image} alt={look.imageAlt || look.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="absolute inset-0 flex flex-col justify-end bg-gradient-to-t from-charcoal/85 via-charcoal/30 to-transparent p-6 text-white"><h3 className="font-serif-display text-xl font-bold">{look.title}</h3><p className="mt-1 text-xs text-white/80">{look.tagline}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold uppercase tracking-wider text-terracotta-light">{s.ctaLabel || "View Edit"} <IconArrowRight className="h-3.5 w-3.5" /></span></div></SafeLink>)}</div></section>;
      case "BOOKS_SHELF": case "BOOKS": return <section key={section.id} className="border-y border-charcoal/10 bg-[#FAF6F0] py-16"><div className="mx-auto max-w-7xl px-4 sm:px-8"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs font-semibold uppercase tracking-widest text-terracotta">{s.eyebrow || "Editorial Monographs"}</span><h2 className="mt-1 font-serif-display text-3xl font-bold text-charcoal sm:text-4xl">{s.title || "From Our Bookshelf"}</h2></div><SafeLink to={s.ctaUrl || "/books"} className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-terracotta hover:underline">{s.ctaLabel || "Explore Books"} <IconArrowRight className="h-4 w-4" /></SafeLink></div><div className="grid gap-6 sm:grid-cols-3">{booksList.slice(0, s.limit || 3).map((book) => <div key={book.id} className="flex flex-col rounded-xl border border-charcoal/10 bg-white p-5 shadow-xs"><div className="mb-4 aspect-[3/4] overflow-hidden rounded-lg bg-[#FAF6F0]"><img src={book.images[0]} alt={book.name} className="h-full w-full object-cover" /></div><h3 className="font-serif-display text-base font-bold text-charcoal">{book.name}</h3>{s.showAuthor !== false && <p className="mt-0.5 text-xs italic text-charcoal-soft">By {book.author}</p>}{s.showDescription !== false && <p className="mt-2 text-xs leading-relaxed text-charcoal-soft">{book.shortDescription}</p>}{s.showPrice !== false && <span className="mt-3 text-sm font-semibold text-terracotta">{formatInr(book.price)}</span>}</div>)}</div></div></section>;
      case "EDITORIAL_BRAND": case "IMAGE_TEXT": return <section key={section.id} className="mx-auto max-w-7xl px-4 py-8 sm:px-8"><div className="grid items-center gap-12 rounded-2xl border border-charcoal/10 bg-white p-8 sm:p-12 lg:grid-cols-12"><div className="space-y-6 lg:col-span-6"><span className="text-xs font-semibold uppercase tracking-widest text-terracotta">{s.eyebrow || "Craftsmanship & Mindful Living"}</span><h2 className="font-serif-display text-3xl font-bold text-charcoal sm:text-4xl lg:text-5xl">{s.title || "Honoring Earth, Metal & Human Hands"}</h2><p className="text-sm leading-relaxed text-charcoal-soft sm:text-base">{s.body}</p><div className="grid grid-cols-2 gap-4">{enabled(s.features || []).map((feature) => <div key={feature.id || feature.title} className={`border-l-2 pl-4 ${feature.accent === "SAGE" ? "border-sage" : "border-terracotta"}`}><p className="font-serif-display text-2xl font-bold text-charcoal">{feature.title}</p><p className="mt-1 text-xs text-charcoal-soft">{feature.description}</p></div>)}</div></div><div className="overflow-hidden rounded-2xl shadow-lg lg:col-span-6"><img src={s.image} alt={s.imageAlt || s.title} className="aspect-[4/3] h-full w-full object-cover" /></div></div></section>;
      case "NEWSLETTER": return <section key={section.id} className="mx-auto max-w-4xl px-4 pt-4 text-center sm:px-8"><div className="space-y-4 rounded-2xl border border-charcoal/10 bg-[#FAF6F0] p-8 sm:p-12"><span className="text-xs font-semibold uppercase tracking-widest text-terracotta">{s.eyebrow || "Join Our Circle"}</span><h2 className="font-serif-display text-3xl font-bold text-charcoal sm:text-4xl">{s.title || "Stories of Craft & New Arrivals"}</h2><p className="mx-auto max-w-md text-xs leading-relaxed text-charcoal-soft sm:text-sm">{s.description}</p>{subscribed ? <div className="rounded-xl bg-sage-light p-4 text-xs font-medium text-green-deep sm:text-sm">{s.successMessage || "Thank you for subscribing to Aadya!"}</div> : <form onSubmit={handleNewsletterSubmit} className="mx-auto mt-6 flex max-w-md flex-col gap-3 sm:flex-row"><input type="email" value={newsletterEmail} onChange={(e) => setNewsletterEmail(e.target.value)} placeholder={s.placeholder || "Enter your email address"} required className="flex-1 rounded-full border border-charcoal/20 bg-white px-5 py-3 text-xs text-charcoal" /><button type="submit" disabled={newsletterStatus === "loading"} className="rounded-full bg-terracotta px-7 py-3 text-xs font-semibold uppercase tracking-wider text-white disabled:opacity-60">{newsletterStatus === "loading" ? (s.loadingLabel || "Subscribing…") : (s.buttonLabel || "Subscribe")}</button></form>}{newsletterStatus === "error" && <p className="text-xs font-medium text-terracotta">{s.errorPrefix ? `${s.errorPrefix} ${newsletterError}` : newsletterError}</p>}</div></section>;
      default: return null;
    }
  };
  const topTypes = new Set(["CIRCULAR_CATEGORY_NAV", "CATEGORY_CIRCLES", "PROMO_STRIP", "PROMO_TICKER", "HERO_CAROUSEL", "HERO", "TRUST_STRIP", "TRUST_BADGES"]);
  const top = sections.filter((s) => topTypes.has(s.type)); const body = sections.filter((s) => !topTypes.has(s.type));
  return <div className="w-full">{top.map(renderSection)}<div className="mt-12 space-y-12 sm:mt-16 sm:space-y-16">{body.map(renderSection)}</div></div>;
}
