import crypto from "node:crypto";
import { prisma } from "../../lib/prisma.js";
import { ApiError } from "../../utils/ApiError.js";
import { hashPassword, verifyPassword } from "../../utils/password.js";
import { hashToken } from "../../utils/secureToken.js";
import { signCustomerAccessToken } from "../../utils/tokens.js";
const expiry = () => new Date(Date.now() + 7 * 86400000);
const raw = () => crypto.randomBytes(24).toString("hex");
const safe = c => ({ id: c.id, name: c.name, email: c.email, phone: c.phone, emailVerifiedAt: c.emailVerifiedAt });
async function session(customer, userAgent) { const token = raw(); await prisma.customerRefreshSession.create({ data: { customerId: customer.id, tokenHash: hashToken(token), expiresAt: expiry(), userAgent: userAgent?.slice(0, 500) } }); return { accessToken: signCustomerAccessToken(customer), refreshToken: token, customer: safe(customer) }; }
export async function register(input, ua) { const exists = await prisma.customer.findUnique({ where: { email: input.email } }); if (exists) throw ApiError.conflict("Unable to create account with these details."); const customer = await prisma.customer.create({ data: { name: input.name, email: input.email, phone: input.phone || null, passwordHash: await hashPassword(input.password) } }); return session(customer, ua); }
export async function login(input, ua) { const c = await prisma.customer.findUnique({ where: { email: input.email } }); if (!c || !(await verifyPassword(input.password, c.passwordHash)) || !c.isActive) throw ApiError.unauthorized("Invalid email or password."); return session(c, ua); }
export async function refresh(token, ua) { if (!token) throw ApiError.unauthorized(); const s = await prisma.customerRefreshSession.findUnique({ where: { tokenHash: hashToken(token) }, include: { customer: true } }); if (!s || s.revokedAt || s.expiresAt <= new Date() || !s.customer.isActive) throw ApiError.unauthorized("Invalid or expired session"); await prisma.customerRefreshSession.update({ where: { id: s.id }, data: { revokedAt: new Date() } }); return session(s.customer, ua); }
export async function logout(token) { if (token) await prisma.customerRefreshSession.updateMany({ where: { tokenHash: hashToken(token), revokedAt: null }, data: { revokedAt: new Date() } }); }
export async function updateProfile(id, input) { return safe(await prisma.customer.update({ where: { id }, data: { name: input.name, phone: input.phone || null } })); }
export async function changePassword(id, input) { const c = await prisma.customer.findUnique({ where: { id } }); if (!c || !(await verifyPassword(input.currentPassword, c.passwordHash))) throw ApiError.unauthorized("Current password is incorrect."); await prisma.$transaction([prisma.customer.update({ where: { id }, data: { passwordHash: await hashPassword(input.newPassword) } }), prisma.customerRefreshSession.updateMany({ where: { customerId: id, revokedAt: null }, data: { revokedAt: new Date() } })]); }
export async function createReset(email) { const c = await prisma.customer.findUnique({ where: { email } }); if (!c) return null; const token = raw(); await prisma.passwordResetToken.deleteMany({ where: { customerId: c.id, usedAt: null } }); await prisma.passwordResetToken.create({ data: { customerId: c.id, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 3600000) } }); return { customer: c, token }; }
export async function resetPassword(input) { const row = await prisma.passwordResetToken.findUnique({ where: { tokenHash: hashToken(input.token) } }); if (!row || row.usedAt || row.expiresAt <= new Date()) throw ApiError.badRequest("This password reset link is invalid or expired."); await prisma.$transaction([prisma.customer.update({ where: { id: row.customerId }, data: { passwordHash: await hashPassword(input.newPassword) } }), prisma.passwordResetToken.update({ where: { id: row.id }, data: { usedAt: new Date() } }), prisma.customerRefreshSession.updateMany({ where: { customerId: row.customerId, revokedAt: null }, data: { revokedAt: new Date() } })]); }
