import { useEffect, useState } from "react";
import { useAdminAuth } from "../../context/AdminAuthContext";
import { adminGetIntegrationStatus, adminSaveIntegration, adminTestIntegration, adminGetShippingBusiness, adminSaveShippingBusiness } from "../../lib/api";

const initialBusiness={provider:"MANUAL",environment:"TEST",autoCreateShipment:false,autoGenerateAwb:false,autoSchedulePickup:false,codAllowed:true,packageDefaults:{length:20,width:15,height:10,weight:.5}};
const Input=({label,type="text",value,onChange,required})=><label className="text-xs">{label}<input required={required} type={type} value={value||""} onChange={onChange} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label>;

export default function AdminIntegrations(){
 const {admin}=useAdminAuth(); const [status,setStatus]=useState(null),[message,setMessage]=useState(""),[business,setBusiness]=useState(initialBusiness),[razorpay,setRazorpay]=useState({environment:"TEST",keyId:"",keySecret:"",webhookSecret:""}),[shiprocket,setShiprocket]=useState({environment:"TEST",apiEmail:"",apiPassword:"",apiBaseUrl:"",webhookSecret:"",enabled:true});
 const load=()=>{adminGetIntegrationStatus().then(r=>setStatus(r.data)).catch(e=>setMessage(e.message));adminGetShippingBusiness().then(r=>setBusiness(v=>({...v,...r.data,packageDefaults:{...v.packageDefaults,...(r.data.packageDefaults||{})}}))).catch(()=>{});}; useEffect(load,[]);
 if(admin?.role!=="SUPER_ADMIN")return <p className="rounded-xl bg-terracotta/10 p-4 text-sm text-terracotta">Only super administrators may manage integrations.</p>;
 const credential=async e=>{e.preventDefault();try{await adminSaveIntegration({provider:"SHIPROCKET",environment:shiprocket.environment,data:shiprocket});setShiprocket(v=>({...v,apiPassword:"",webhookSecret:""}));setMessage("Shiprocket credentials saved securely.");load();}catch(err){setMessage(err.message)}};
 const configured=status?.credentials?.find(x=>x.provider==="SHIPROCKET");
 return <div className="max-w-4xl space-y-6"><div><p className="text-xs font-semibold uppercase tracking-widest text-terracotta">Settings</p><h1 className="font-serif-display text-3xl text-charcoal">Integrations</h1></div>{message&&<p className="rounded-xl bg-sage-light p-3 text-sm text-green-deep">{message}</p>}
 <section className="rounded-2xl border border-charcoal/10 bg-white p-5"><h2 className="font-serif-display text-xl">Razorpay</h2><form onSubmit={async e=>{e.preventDefault();try{await adminSaveIntegration({provider:"RAZORPAY",environment:razorpay.environment,data:razorpay});setMessage("Razorpay credentials saved securely.")}catch(err){setMessage(err.message)}}} className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Key ID" value={razorpay.keyId} required onChange={e=>setRazorpay({...razorpay,keyId:e.target.value})}/><Input label="Key Secret" type="password" value={razorpay.keySecret} required onChange={e=>setRazorpay({...razorpay,keySecret:e.target.value})}/><Input label="Webhook secret" type="password" value={razorpay.webhookSecret} onChange={e=>setRazorpay({...razorpay,webhookSecret:e.target.value})}/><button className="rounded-full bg-charcoal px-4 py-2 text-xs text-white">Save</button></form></section>
 <section className="rounded-2xl border border-charcoal/10 bg-white p-5"><h2 className="font-serif-display text-xl">Shipping provider</h2><form onSubmit={async e=>{e.preventDefault();try{await adminSaveShippingBusiness({...business,packageDefaults:Object.fromEntries(Object.entries(business.packageDefaults).map(([k,v])=>[k,Number(v)]))});setMessage("Shipping settings saved.")}catch(err){setMessage(err.message)}}} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs">Provider<select value={business.provider} onChange={e=>setBusiness({...business,provider:e.target.value})} className="mt-1 w-full rounded-lg border p-2 text-sm"><option>MANUAL</option><option>SHIPROCKET</option><option disabled>DELHIVERY</option></select></label><label className="text-xs">Environment<select value={business.environment} onChange={e=>setBusiness({...business,environment:e.target.value})} className="mt-1 w-full rounded-lg border p-2 text-sm"><option>TEST</option><option>LIVE</option></select></label><p className="text-xs text-charcoal-soft sm:col-span-2">Delhivery: Not available yet — requires contracted API/webhook specification.</p>{[["autoCreateShipment","Auto-create shipment"],["autoGenerateAwb","Auto-generate AWB"],["autoSchedulePickup","Auto-schedule pickup"],["codAllowed","COD allowed"]].map(([k,l])=><label key={k} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={business[k]} onChange={e=>setBusiness({...business,[k]:e.target.checked})}/>{l}</label>)}<div className="grid grid-cols-2 gap-3 sm:col-span-2 sm:grid-cols-4">{Object.entries(business.packageDefaults).map(([k,v])=><Input key={k} label={k} type="number" value={v} onChange={e=>setBusiness({...business,packageDefaults:{...business.packageDefaults,[k]:e.target.value}})}/>)}</div><button className="rounded-full bg-charcoal px-4 py-2 text-xs text-white">Save shipping settings</button></form></section>
 <section className="rounded-2xl border border-charcoal/10 bg-white p-5"><h2 className="font-serif-display text-xl">Shiprocket</h2><p className="mt-1 text-xs text-charcoal-soft">{configured?.configured?`Configured · ${configured.testStatus||"not tested"}${configured.lastTestedAt?` · last tested ${new Date(configured.lastTestedAt).toLocaleString("en-IN")}`:""}`:"Not configured"}</p><form onSubmit={credential} className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Email / username" type="email" value={shiprocket.apiEmail} required onChange={e=>setShiprocket({...shiprocket,apiEmail:e.target.value})}/><Input label="Password" type="password" value={shiprocket.apiPassword} required onChange={e=>setShiprocket({...shiprocket,apiPassword:e.target.value})}/><Input label="API/base URL (optional)" type="url" value={shiprocket.apiBaseUrl} onChange={e=>setShiprocket({...shiprocket,apiBaseUrl:e.target.value})}/><Input label="Webhook secret" type="password" value={shiprocket.webhookSecret} onChange={e=>setShiprocket({...shiprocket,webhookSecret:e.target.value})}/><label className="text-xs">Environment<select value={shiprocket.environment} onChange={e=>setShiprocket({...shiprocket,environment:e.target.value})} className="mt-1 w-full rounded-lg border p-2 text-sm"><option>TEST</option><option>LIVE</option></select></label><div className="flex items-end gap-2"><button className="rounded-full bg-charcoal px-4 py-2 text-xs text-white">Replace Credentials</button><button type="button" onClick={async()=>{try{await adminTestIntegration("SHIPROCKET",shiprocket.environment);setMessage("Connection test completed.");load()}catch(e){setMessage(e.message)}}} className="rounded-full border px-4 py-2 text-xs">Test Connection</button></div></form></section></div>;
}
