import { afterAll, beforeEach, describe, expect, it } from "vitest";
import request from "supertest";
import { createApp } from "../src/app.js"; import { env } from "../src/config/env.js"; import { prisma } from "../src/lib/prisma.js"; import { registerCustomer, resetDb, seedTestAdmin } from "./helpers.js";
const app=createApp();async function login(role="SUPER_ADMIN"){await seedTestAdmin({role});return (await request(app).post("/api/admin/auth/login").send({email:env.admin.email,password:env.admin.password})).body.data.accessToken;}beforeEach(resetDb);afterAll(async()=>{await resetDb();await prisma.$disconnect();});
describe("admin customer and admin-user management",()=>{
 it("lists/searches customers safely and deactivation revokes refresh sessions",async()=>{const admin=await login(), registered=await registerCustomer(app,{name:"Anaya Test",email:"anaya@example.com",phone:"9999999999"});const list=await request(app).get("/api/admin/customers?search=anaya").set("Authorization",`Bearer ${admin}`);expect(list.status).toBe(200);expect(list.body.data[0]).not.toHaveProperty("passwordHash");const id=registered.customer.id;expect((await request(app).patch(`/api/admin/customers/${id}/status`).set("Authorization",`Bearer ${admin}`).send({isActive:false})).status).toBe(200);expect((await registered.agent.post("/api/auth/refresh")).status).toBe(401);expect((await request(app).post("/api/auth/login").send({email:"anaya@example.com",password:registered.credentials.password})).status).toBe(401);});
 it("limits admin-user management to super admins and protects the final super admin",async()=>{const superToken=await login();const created=await request(app).post("/api/admin/admin-users").set("Authorization",`Bearer ${superToken}`).send({name:"Operator",email:"operator@example.com",password:"SafePassword123!",role:"ADMIN"});expect(created.status).toBe(201);expect(created.body.data).not.toHaveProperty("passwordHash");expect((await request(app).patch(`/api/admin/admin-users/${created.body.data.id}/status`).set("Authorization",`Bearer ${superToken}`).send({isActive:false})).status).toBe(200);const superUser=await prisma.adminUser.findUnique({where:{email:env.admin.email}});expect((await request(app).patch(`/api/admin/admin-users/${superUser.id}/status`).set("Authorization",`Bearer ${superToken}`).send({isActive:false})).status).toBe(400);});
 it("rejects customer and ADMIN tokens for admin user routes",async()=>{const customer=await registerCustomer(app);expect((await request(app).get("/api/admin/admin-users").set("Authorization",`Bearer ${customer.accessToken}`)).status).toBe(401);const admin=await login("ADMIN");expect((await request(app).get("/api/admin/admin-users").set("Authorization",`Bearer ${admin}`)).status).toBe(403);});
});
