import { afterAll, beforeEach, describe, expect, it } from "vitest";
import request from "supertest";
import { createApp } from "../src/app.js"; import { env } from "../src/config/env.js"; import { prisma } from "../src/lib/prisma.js"; import { resetDb, seedTestAdmin, seedTestCategory, seedTestProduct } from "./helpers.js";
const app=createApp(); async function token(){await seedTestAdmin();return (await request(app).post("/api/admin/auth/login").send({email:env.admin.email,password:env.admin.password})).body.data.accessToken;} beforeEach(resetDb);afterAll(async()=>{await resetDb();await prisma.$disconnect();});
describe("collections, settings and newsletter",()=>{
 it("manages collections and exposes only active products publicly",async()=>{const t=await token(), category=await seedTestCategory(), product=await seedTestProduct({category}), hidden=await seedTestProduct({category,name:"hidden",slug:"hidden",isActive:false}); const c=await request(app).post("/api/admin/collections").set("Authorization",`Bearer ${t}`).send({title:"Featured"}); expect(c.status).toBe(201); expect((await request(app).put(`/api/admin/collections/${c.body.data.id}/products`).set("Authorization",`Bearer ${t}`).send({productIds:[product.id,hidden.id]})).status).toBe(200); const publicDetail=await request(app).get("/api/collections/featured"); expect(publicDetail.status).toBe(200); expect(publicDetail.body.data.products.map(x=>x.product.id)).toContain(product.id); await request(app).patch(`/api/admin/collections/${c.body.data.id}`).set("Authorization",`Bearer ${t}`).send({isActive:false}); expect((await request(app).get("/api/collections")).body.data).toEqual([]);});
 it("allows only safe setting keys and returns no environment secrets",async()=>{const t=await token();const res=await request(app).put("/api/admin/settings").set("Authorization",`Bearer ${t}`).send({standardShippingAmount:99,freeShippingThreshold:2000,announcementBar:{text:"Hello",active:true},supportEmail:"help@example.com",seoDefaults:{title:"Aadya",description:"Shop"}});expect(res.status).toBe(200);expect((await request(app).put("/api/admin/settings").set("Authorization",`Bearer ${t}`).send({jwtSecret:"no"})).status).toBe(400);const pub=await request(app).get("/api/settings");expect(JSON.stringify(pub.body)).not.toContain("test-access-secret");expect(pub.body.data.standardShippingAmount).toBe(99);});
 it("normalizes newsletter subscriptions without duplicate rows",async()=>{expect((await request(app).post("/api/newsletter/subscribe").send({email:"  TEST@Example.com "})).status).toBe(201);expect((await request(app).post("/api/newsletter/subscribe").send({email:"test@example.com"})).status).toBe(201);expect(await prisma.newsletterSubscriber.count()).toBe(1);expect((await request(app).post("/api/newsletter/subscribe").send({email:"nope"})).status).toBe(400);});
});
